# Generated by Django 4.2.6 on 2023-11-21 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_Orden', models.AutoField(primary_key=True, serialize=False)),
                ('no_Orden', models.CharField(max_length=20)),
                ('fechaPedido', models.DateTimeField(default=datetime.datetime(2023, 11, 21, 2, 44, 35, 643479, tzinfo=datetime.timezone.utc))),
                ('nombreProd', models.CharField(max_length=20)),
                ('codigoProd', models.CharField(max_length=6)),
                ('cantSolicitada', models.IntegerField()),
                ('precioUnitario', models.IntegerField()),
                ('totalPedido', models.IntegerField()),
                ('nombreProv', models.CharField(max_length=50)),
                ('dirProveedor', models.CharField(max_length=100)),
                ('telefonoProv', models.IntegerField()),
                ('emailProv', models.CharField(max_length=100)),
                ('dirEntrega', models.CharField(max_length=100)),
                ('fechaEntrega', models.DateTimeField(null=True)),
                ('metodoPago', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='col_mun',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='n_seg_social',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='num_ext',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='num_int',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='num_tel',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='t_sangre',
        ),
        migrations.AddField(
            model_name='rolextra',
            name='pedidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolextra',
            name='soporteenviar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolextra',
            name='usuariosRecuperacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
