# Generated by Django 4.2.6 on 2023-11-21 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0002_ordenes_remove_usuario_calle_remove_usuario_col_mun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='fechaPedido',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 5, 53, 41, 592142, tzinfo=datetime.timezone.utc)),
        ),
    ]
